version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ci_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: cotedivoire_names
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ci_network

  elasticsearch:
    image: elasticsearch:8.8.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - ci_network

  django:
    build: ./djangoproject
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi
    volumes:
      - ./djangoproject:/app
    ports:
      - "8000:8000"
    environment:
      - ES_HOST=elasticsearch
      - DATABASE_URL=postgresql://ci_user:strongpassword@postgres/cotedivoire_names
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - ci_network

volumes:
  postgres_data:
  elastic_data:

networks:
  ci_network: