name: CI/CD - Builder, Pousser & Deployer l'image sur K8s

on:
  push:
    tags:
      - "v*"

jobs:
  test-build-deploy:
    name: Test, Build & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Tester l'API
        run: pytest

      - name: Vérifier que le tag est sur un commit de main
        run: |
          git fetch origin main --depth=1000
          BRANCH=$(git branch -r --contains ${{ github.sha }} | grep origin/main || true)
          if [ -z "$BRANCH" ]; then
            echo "Le tag n'est pas sur un commit de main. Fin du workflow."
            exit 1
          fi
        shell: bash

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: datalab-registry
          password: ${{ secrets.GHCR_PAT }}

      - name: Builder & pousser l'image docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/datalab-registry/es_api_prod3:${{ github.ref_name }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Connexion à kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Déployer sur Kubernetes
        run: |
          kubectl set image deployment/es-api es-api=ghcr.io/datalab-registry/es_api_prod3:${{ github.ref_name }} -n production











